export default {
	SET_USERS_DATA: 'SET_USERS_DATA',
	SET_ERROR: 'SET_ERROR',
	CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
	RADIO_CHANGE: 'RADIO_CHANGE',
	SET_FILTER_VALUE: 'SET_FILTER_VALUE',
	CHANGE_FAVOURITE: 'CHANGE_FAVOURITE',
}
